@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%"

set "PYTHON_CMD=python"
if defined PYTHON_EXE set "PYTHON_CMD=%PYTHON_EXE%"

%PYTHON_CMD% -c "import sys; print(sys.executable)" >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python interpreter not found.
    echo [HINT]  set PYTHON_EXE=full\path\to\python.exe
    pause
    exit /b 1
)

for /f "usebackq delims=" %%I in (`%PYTHON_CMD% -c "import os,sys; print(os.path.dirname(sys.executable))"`) do set "PY_ENV_DIR=%%I"
if defined PY_ENV_DIR (
    set "PATH=%PY_ENV_DIR%;%PY_ENV_DIR%\Scripts;%PY_ENV_DIR%\Library\bin;%PY_ENV_DIR%\Library\usr\bin;%PY_ENV_DIR%\Library\mingw-w64\bin;%PATH%"
)

%PYTHON_CMD% -m PyInstaller --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] PyInstaller is not installed in current Python environment.
    echo [HINT]  %PYTHON_CMD% -m pip install pyinstaller
    pause
    exit /b 1
)

set "ICON_ARGS="
set "DATA_ARGS="
if exist "tray_icon.ico" (
    set "ICON_ARGS=--icon tray_icon.ico"
    set "DATA_ARGS=--add-data tray_icon.ico;."
)

set "MODE=--onedir"
set "HIDE_CONTROL_WINDOW=0"

:parse_args
if "%~1"=="" goto args_parsed
if /I "%~1"=="--onefile" (
    set "MODE=--onefile"
    shift
    goto parse_args
)
if /I "%~1"=="--hide-control-window" (
    set "HIDE_CONTROL_WINDOW=1"
    shift
    goto parse_args
)
echo [ERROR] Unknown argument: %~1
echo [HINT] Supported args: --onefile --hide-control-window
pause
exit /b 1

:args_parsed

set "BUILD_TS="
for /f "usebackq delims=" %%T in (`%PYTHON_CMD% -c "from datetime import datetime; print(datetime.now().strftime('%%Y%%m%%d_%%H%%M%%S'))"`) do set "BUILD_TS=%%T"
if not defined BUILD_TS (
    echo [ERROR] Failed to generate build timestamp.
    pause
    exit /b 1
)
set "DIST_DIR=dist_%BUILD_TS%"
echo [INFO] Dist output folder: %DIST_DIR%
if "%HIDE_CONTROL_WINDOW%"=="1" (
    echo [INFO] Startup behavior: hide control window to tray.
) else (
    echo [INFO] Startup behavior: show control window.
)

set "ENTRY_SCRIPT=desktop_reminder.py"
set "TEMP_ENTRY_SCRIPT="
if "%HIDE_CONTROL_WINDOW%"=="1" (
    set "TEMP_ENTRY_SCRIPT=!SCRIPT_DIR!_build_entry_hide_control_window.py"
    (
        echo # Auto-generated by build_exe.bat. Do not commit.
        echo from __future__ import annotations
        echo import sys
        echo from reminder.application.runner import main
        echo if __name__ == "__main__":
        echo     raise SystemExit^(main^(sys.argv[1:] + ["--hide-control-window"]^)^)
    ) > "!TEMP_ENTRY_SCRIPT!"
    set "ENTRY_SCRIPT=!TEMP_ENTRY_SCRIPT!"
)

%PYTHON_CMD% -m PyInstaller --noconfirm --clean --windowed %MODE% --distpath "%SCRIPT_DIR%%DIST_DIR%" --name DesktopReminder %ICON_ARGS% %DATA_ARGS% "%ENTRY_SCRIPT%"
set "BUILD_EXIT_CODE=%ERRORLEVEL%"

if defined TEMP_ENTRY_SCRIPT if exist "!TEMP_ENTRY_SCRIPT!" del /f /q "!TEMP_ENTRY_SCRIPT!" >nul 2>&1

if not "%BUILD_EXIT_CODE%"=="0" (
    echo [ERROR] Build failed.
    pause
    exit /b 1
)

echo [OK] Build succeeded.
if /I "%MODE%"=="--onefile" (
    echo [OUT] %SCRIPT_DIR%%DIST_DIR%\DesktopReminder.exe
) else (
    echo [OUT] %SCRIPT_DIR%%DIST_DIR%\DesktopReminder\DesktopReminder.exe
    echo [NOTE] onedir mode avoids the extra bootstrap process of onefile.
)
exit /b 0
